<?php
/**
 * Copyright © Exocortex, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
?>
<div class="" id="clara-player" style="height:1000px">
  <div id="root"></div>
</div>
<div id="clara-panelControl"></div>
<div id="clara-form-configurations-wrapper"></div>


