<?php
/**
 * Copyright © Exocortex, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$product = $block->getProduct();
?>
<div class="" id="clara-player" style="height:1000px">
  <div id="root"></div>
</div>
<script type="text/javascript" src="js/threekit/main.js"></script>
<script type="text/javascript">
  console.log("inline js called");
  console.log(<?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>);
  console.log(<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($product)?>);
  var threekitHandle = new ThreekitConfigurator();
</script>

