<?php
/**
 * Copyright © Exocortex, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $product = $this->getProduct() ?>
<div class="" id="clara-player" style="height:1000px">
  <div id="root"></div>
</div>
<script type="text/javascript" src=<?php echo $this->getJsUrl('js/threekit/main.js') ?>></script>
<script type="text/javascript">
  var confOptions = {
    optionConfig: <?php /* @escapeNotVerified */ echo $this->getJsonConfig()?>,
    formKey: <?php /* @escapeNotVerified */ echo json_encode(Mage::getSingleton('core/session')->getFormKey())?>,
    submitUrl: <?php /* @escapeNotVerified */ echo json_encode($this->getSubmitUrl($product, array('_secure' => $this->_isSecure())))?>,
    productId: <?php /* @escapeNotVerified */ echo json_encode($product->getId())?>
  };
  var threekitHandle = new ThreekitConfigurator(confOptions);
</script>

